[package]
name = "mqttui"
description = "Subscribe to a MQTT Topic or publish something quickly from the terminal"
version = "0.13.0"
license = "GPL-3.0-or-later"
repository = "https://github.com/EdJoPaTo/mqttui"
authors = ["EdJoPaTo <mqttui-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[build-dependencies]
clap = "2"

[dependencies]
anyhow = "1"
chrono = "0.4"
crossterm = "0.20"
json = "0.12"
rand = "0.8"
rumqttc = "0.7"
tui-tree-widget = "0.6"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.tui]
version = "0.15"
default-features = false
features = ["crossterm"]
