[package]
name = "mqttui"
version = "0.12.0"
license = "GPL-3.0-or-later"
description = "Subscribe to a MQTT Topic or publish something quickly from the terminal"
authors = ["EdJoPaTo <mqttui-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = "0.4"
crossterm = "0.19"
json = "0.12"
rand = "0.8"
rumqttc = "0.6"
tui-tree-widget = "0.6"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.tui]
version = "0.15"
default-features = false
features = ["crossterm"]
