[package]
name = "mqttui"
description = "Subscribe to a MQTT Topic or publish something quickly from the terminal"
version = "0.15.0"
license = "GPL-3.0-or-later"
repository = "https://github.com/EdJoPaTo/mqttui"
authors = ["EdJoPaTo <mqttui-rust@edjopato.de>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[build-dependencies]
clap = { version = "3", features = ["cargo"] }
clap_complete = "3"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "3", features = ["cargo", "env", "wrap_help"] }
crossterm = "0.23"
json = "0.12"
rand = "0.8"
rumqttc = "0.11"
tui = "0.17"
tui-tree-widget = "0.8"
